trigger:
- main

pool:
  name: Default

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.x'

- script: dotnet build mari_quiz4_dotnet/mari_quiz4_dotnet.csproj --configuration $(buildConfiguration)
  displayName: 'Build project'

- script: dotnet publish mari_quiz4_dotnet/mari_quiz4_dotnet.csproj -c $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)
  displayName: 'Publish project'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
